/* auto generate from actions_owl.config, DONNOT EDIT!*/
#ifndef __ACTIONS_CONFIGH_H__
#define __ACTIONS_CONFIGH_H__
#define  ACTIONS_FEATURE_KEYTUNE_DEFAULT_ON  1
#define  ACTIONS_OPT_DISABLE_MEDIA_INFO_VIDEO_TRACK_LAGGING  1
#define  ACTIONS_PROFILE_LIBC_LD 1
#define  ACTIONS_FEATURE_SENCE_DETECTED_DEFAULT_ON  1
#define  ACTIONS_FEATURE_DEBUG_FPS_DEFAULT_ON  1
#define  ACTIONS_FEATURE_HDMI_ALLOW_VOLUME_ADJUSTING  1
#define  ACTIONS_FEATURE_SAME_VOLUME_CONFIGURABLE  1
#define  ACTIONS_FEATURE_STOP_PLAY_WHEN_USB_ACCESSARY_PLUGGED  1
#define  ACTIONS_FEATURE_AUDIO_OUTPUT_PRIORITY_CONFIGURABLE  1
#define  ACTIONS_FEATURE_SAFE_MEDIA_TIME_CONFIG_ON  1
#define  ACTIONS_FEATURE_SHUTDOWN_PA_WHEN_MUTED_ON  1
#define  ACTIONS_OPT_SAMPLE_USE_NEON  1
#define  ACTIONS_FEATURE_HW_ROTATION_DEFAULT_ON 1
#define  ACTIONS_BUGFIX_ID3_MESSY  1
#define  ACTIONS_FEATURE_HDMI_USE_OPAQUE_FORMAT  1
#define  NUM_FRAMEBUFFER_SURFACE_BUFFERS  3
#define  ACTIONS_FEATURE_FLASHPLAYER_PLUGIN 1
#define  ACTIONS_FEATURE_CHECK_GPU_READY 1
#endif
