obj-$(CONFIG_VIDEO_OWL_DSS) += owl_dss.o

# Core DSS files
owl_dss-y := core.o display.o dss_features.o de.o manager.o overlay.o
owl_dss-$(CONFIG_VIDEO_OWL_MMU_SUPPORT) += mmu.o

owl_dss-$(CONFIG_VIDEO_OWL_DE_ATM7059) += de_atm7059.o

