#
# (C) Copyright 2000-2012
# Actions Semi .Inc
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#
obj-y += owl.o owl_afi.o owl_boot_fdt.o
obj-$(CONFIG_ANDROID_RECOVERY) += recovery.o
obj-$(CONFIG_OWL_DISPLAY_LCD)	+= owl_dss.o
obj-$(CONFIG_USBDOWNLOAD_GADGET) += gadget.o
