/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma version(1)
#pragma rs java_package_name(android.renderscript.cts)

// Don't edit this file!  It is auto-generated by frameworks/rs/api/gen_runtime.


uchar __attribute__((kernel)) testAbsCharUchar(char inValue) {
    return abs(inValue);
}

uchar2 __attribute__((kernel)) testAbsChar2Uchar2(char2 inValue) {
    return abs(inValue);
}

uchar3 __attribute__((kernel)) testAbsChar3Uchar3(char3 inValue) {
    return abs(inValue);
}

uchar4 __attribute__((kernel)) testAbsChar4Uchar4(char4 inValue) {
    return abs(inValue);
}

ushort __attribute__((kernel)) testAbsShortUshort(short inValue) {
    return abs(inValue);
}

ushort2 __attribute__((kernel)) testAbsShort2Ushort2(short2 inValue) {
    return abs(inValue);
}

ushort3 __attribute__((kernel)) testAbsShort3Ushort3(short3 inValue) {
    return abs(inValue);
}

ushort4 __attribute__((kernel)) testAbsShort4Ushort4(short4 inValue) {
    return abs(inValue);
}

uint __attribute__((kernel)) testAbsIntUint(int inValue) {
    return abs(inValue);
}

uint2 __attribute__((kernel)) testAbsInt2Uint2(int2 inValue) {
    return abs(inValue);
}

uint3 __attribute__((kernel)) testAbsInt3Uint3(int3 inValue) {
    return abs(inValue);
}

uint4 __attribute__((kernel)) testAbsInt4Uint4(int4 inValue) {
    return abs(inValue);
}
