/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma version(1)
#pragma rs java_package_name(android.renderscript.cts)

// Don't edit this file!  It is auto-generated by frameworks/rs/api/gen_runtime.

rs_allocation gAllocInRhs;

float __attribute__((kernel)) testFastDistanceFloatFloatFloat(float inLhs, unsigned int x) {
    float inRhs = rsGetElementAt_float(gAllocInRhs, x);
    return fast_distance(inLhs, inRhs);
}

float __attribute__((kernel)) testFastDistanceFloat2Float2Float(float2 inLhs, unsigned int x) {
    float2 inRhs = rsGetElementAt_float2(gAllocInRhs, x);
    return fast_distance(inLhs, inRhs);
}

float __attribute__((kernel)) testFastDistanceFloat3Float3Float(float3 inLhs, unsigned int x) {
    float3 inRhs = rsGetElementAt_float3(gAllocInRhs, x);
    return fast_distance(inLhs, inRhs);
}

float __attribute__((kernel)) testFastDistanceFloat4Float4Float(float4 inLhs, unsigned int x) {
    float4 inRhs = rsGetElementAt_float4(gAllocInRhs, x);
    return fast_distance(inLhs, inRhs);
}
