#Makefile for actions si or isp driver and the sensors of actions support

obj-y				+= owl_camera/
obj-y       		+= gc2035/
obj-y				+= gc0308/
obj-y				+= gc2155/
obj-y				+= gc0312/
obj-y				+= gc2145/
obj-y				+= gc0328/
obj-y				+= gc0329/
obj-y				+= sp0a19/
obj-y				+= hi257/
obj-y				+= hi708/
obj-y				+= ov5640/
obj-y				+= ov2686/
obj-y				+= soc5140/
obj-y				+= sp2519/
obj-y				+= sp0718/
obj-y				+= siv121du/
obj-y				+= flashlight/
obj-y				+= sensor_detect/