#ifndef __CEC_REG_H__
#define __CEC_REG_H__
                                 
//--------------Bits Location------------------------------------------//
//--------------HDMI-------------------------------------------//
//--------------Register Address---------------------------------------//
#define  HDMI_BASE                                                         0xB02C0000
#define  HDMI_VICTL                                                        (0x0000)
#define  HDMI_VIVSYNC                                                      (0x0004)
#define  HDMI_VIVHSYNC                                                     (0x0008)
#define  HDMI_VIALSEOF                                                     (0x000C)
#define  HDMI_VIALSEEF                                                     (0x0010)
#define  HDMI_VIADLSE                                                      (0x0014)
#define  HDMI_AIFRAMEC                                                     (0x0020)
#define  HDMI_AICHSTABYTE0TO3                                              (0x0024)
#define  HDMI_AICHSTABYTE4TO7                                              (0x0028)
#define  HDMI_AICHSTABYTE8TO11                                             (0x002C)
#define  HDMI_AICHSTABYTE12TO15                                            (0x0030)
#define  HDMI_AICHSTABYTE16TO19                                            (0x0034)
#define  HDMI_AICHSTABYTE20TO23                                            (0x0038)
#define  HDMI_AICHSTASCN                                                   (0x003C)
#define  HDMI_VR                                                           (0x0050)
#define  HDMI_CR                                                           (0x0054)
#define  HDMI_SCHCR                                                        (0x0058)
#define  HDMI_ICR                                                          (0x005C)
#define  HDMI_SCR                                                          (0x0060)
#define  HDMI_LPCR                                                         (0x0064)
#define  HDCP_CR                                                           (0x0068)
#define  HDCP_SR                                                           (0x006C)
#define  HDCP_ANLR                                                         (0x0070)
#define  HDCP_ANMR                                                         (0x0074)
#define  HDCP_ANILR                                                        (0x0078)
#define  HDCP_ANIMR                                                        (0x007C)
#define  HDCP_DPKLR                                                        (0x0080)
#define  HDCP_DPKMR                                                        (0x0084)
#define  HDCP_LIR                                                          (0x0088)
#define  HDCP_SHACR                                                        (0x008C)
#define  HDCP_SHADR                                                        (0x0090)
#define  HDCP_ICR                                                          (0x0094)
#define  HDCP_KMMR                                                         (0x0098)
#define  HDCP_KMLR                                                         (0x009C)
#define  HDCP_MILR                                                         (0x00A0)
#define  HDCP_MIMR                                                         (0x00A4)
#define  HDCP_KOWR                                                         (0x00A8)
#define  HDCP_OWR                                                          (0x00AC)
#define  TMDS_STR0                                                         (0x00B8)
#define  TMDS_STR1                                                         (0x00BC)
#define  TMDS_EODR0                                                        (0x00C0)
#define  TMDS_EODR1                                                        (0x00C4)
#define  HDMI_ASPCR                                                        (0x00D0)
#define  HDMI_ACACR                                                        (0x00D4)
#define  HDMI_ACRPCR                                                       (0x00D8)
#define  HDMI_ACRPCTSR                                                     (0x00DC)
#define  HDMI_ACRPPR                                                       (0x00E0)
#define  HDMI_GCPCR                                                        (0x00E4)
#define  HDMI_RPCR                                                         (0x00E8)
#define  HDMI_RPRBDR                                                       (0x00EC)
#define  HDMI_OPCR                                                         (0x00F0)
#define  HDMI_DIPCCR                                                       (0x00F4)
#define  HDMI_ORP6PH                                                       (0x00F8)
#define  HDMI_ORSP6W0                                                      (0x00FC)
#define  HDMI_ORSP6W1                                                      (0x0100)
#define  HDMI_ORSP6W2                                                      (0x0104)
#define  HDMI_ORSP6W3                                                      (0x0108)
#define  HDMI_ORSP6W4                                                      (0x010C)
#define  HDMI_ORSP6W5                                                      (0x0110)
#define  HDMI_ORSP6W6                                                      (0x0114)
#define  HDMI_ORSP6W7                                                      (0x0118)
#define  HDMI_CECCR                                                        (0x011C)
#define  HDMI_CECRTCR                                                      (0x0120)
#define  HDMI_CECRXCR                                                      (0x0124)
#define  HDMI_CECTXCR                                                      (0x0128)
#define  HDMI_CECTXDR                                                      (0x012C)
#define  HDMI_CECRXDR                                                      (0x0130)
#define  HDMI_CECRXTCR                                                     (0x0134)
#define  HDMI_CECTXTCR0                                                    (0x0138)
#define  HDMI_CECTXTCR1                                                    (0x013C)
#define  HDMI_CRCCR                                                        (0x0140)
#define  HDMI_CRCDOR                                                       (0x0144)
#define  HDMI_TX_1                                                         (0x0154)
#define  HDMI_TX_2                                                         (0x0158)
#define  CEC_DDC_HPD                                                       (0x015C)


#define CES_RX_CTRL_ENABLE                                                    (1 << 15)
#define CES_RX_CTRL_RESET                                                     (1 << 14)
#define CES_RX_IRQ_ENABLE                                                     (1 << 12)
#define CES_RX_EOM                                                            (1 << 7)
#define CES_RX_IRQ_PENDDING                                                   (1 << 6)
#define CES_RX_FIFO_RRROR                                                     (1 << 5)
#define CES_RX_FIFO_NUM_MASK                                                  (1 << 5)

#define CES_TX_ADDR_EN                                                        (1 << 20)   
#define CES_TX_CTRL_ENABLE                                                    (1 << 15)
#define CES_TX_CTRL_RESET                                                     (1 << 14)
#define CES_TX_IRQ_ENABLE                                                     (1 << 12)
#define CES_TX_EOM                                                            (1 << 7)
#define CES_TX_IRQ_PENDDING                                                   (1 << 6)
#define CES_TX_FIFO_RRROR                                                     (1 << 5)
#define CES_TX_FIFO_NUM_MASK                                                  (1 << 5)
#define CES_TX_CTRL_BCAST                                                     (0x0f << 8)
#endif  //__CEC_REG_H__

