
# Configuration
#RTK_BT_FIRMWARE_DIR := firmware/rtl8723bu
RTK_BT_FIRMWARE_DIR := firmware

LOCAL_PATH := $(call my-dir)


ifeq ($(BUILD_RTL8723BU), true)

include $(CLEAR_VARS)
LOCAL_MODULE := rtl8723bu_config
LOCAL_MODULE_TAGS := optional eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/$(RTK_BT_FIRMWARE_DIR)
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_BT_MODULES +=$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rtl8723bu_fw
LOCAL_MODULE_TAGS := optional eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/$(RTK_BT_FIRMWARE_DIR)
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_BT_MODULES +=$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

endif










