#
# Makefile for Invensense inv-mpu-iio device.
#

obj-$(CONFIG_IIO_INV_MPU6515) += gyrosensor_inv_mpu6515_iio.o
gyrosensor_inv_mpu6515_iio-objs := inv_mpu_core.o
gyrosensor_inv_mpu6515_iio-objs += inv_mpu_ring.o
gyrosensor_inv_mpu6515_iio-objs += inv_mpu_trigger.o
gyrosensor_inv_mpu6515_iio-objs += inv_mpu_misc.o
gyrosensor_inv_mpu6515_iio-objs += inv_mpu3050_iio.o
gyrosensor_inv_mpu6515_iio-objs += dmpDefaultMPU6050.o
gyrosensor_inv_mpu6515_iio-objs += inv_slave_compass.o
gyrosensor_inv_mpu6515_iio-objs += inv_slave_pressure.o

