#
# Makefile for the gsensor drivers
#

obj-$(CONFIG_GSENSOR_BMA250_DUMMY)    += gsensor_bma250_dummy.o
gsensor_bma250_dummy-objs := bma250_dummy.o
obj-$(CONFIG_GSENSOR_BMA220)		  += gsensor_bma220.o
gsensor_bma220-objs := bma220.o
obj-$(CONFIG_GSENSOR_BMA222)		  += gsensor_bma222.o
gsensor_bma222-objs := bma222.o
obj-$(CONFIG_GSENSOR_BMA250)		  += gsensor_bma250.o
gsensor_bma250-objs := bma250.o
obj-$(CONFIG_GSENSOR_MC3210)		  += gsensor_mc3210.o
gsensor_mc3210-objs := mc3210.o
obj-$(CONFIG_GSENSOR_MC3230)		  += gsensor_mc3230.o
gsensor_mc3230-objs := mc3230.o
obj-$(CONFIG_GSENSOR_MC3232)		  += gsensor_mc3232.o
gsensor_mc3232-objs := mc3232.o
obj-$(CONFIG_GSENSOR_MC3236)		  += gsensor_mc3236.o
gsensor_mc3236-objs := mc3236.o
obj-$(CONFIG_GSENSOR_KIONIX)      += kionix/
obj-$(CONFIG_GSENSOR_STK8312)		  += stk8312/
obj-$(CONFIG_GSENSOR_STK8313)		  += stk8313/
obj-$(CONFIG_GSENSOR_MMA7660)		  += mma7660/
obj-$(CONFIG_GSENSOR_MIR3DA)		  += mir3da/
obj-$(CONFIG_GSENSOR_DETECT)		  += gsensor_detect.o